global using CommunityToolkit.Diagnostics;
global using Namotion.Reflection;
global using BaseComponents.API.Extensions;
global using BaseComponents.API.Endpoints;
global using BaseComponents.Behavior;
global using BaseComponents.Observability.Extensions;
global using BaseComponents.Behavior.Interfaces;
global using BaseComponents.Behavior.Extensions.ServiceCollectionExtensions;
global using EventHandlersExample.API.Events;